---
# Changes here will be overwritten by Copier
_commit: v2.6.0
_src_path: gh:remerge/template
is_golang_library: true
project_id: go-timestr
project_license: private
project_name: Cached Time Strings for Go
project_owner: core
project_type: default
use_ansible: false
use_consul: false
use_golang: true
use_nomad: false
use_python: false
use_terraform: false
