---
default_stages:
  - commit

default_install_hook_types:
  - commit-msg
  - pre-commit
  - prepare-commit-msg

repos:
  # https://github.com/pre-commit/pre-commit-hooks/tags
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: trailing-whitespace
        exclude: "^.gitignore$"

  # https://github.com/pre-commit/mirrors-prettier/tags
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        exclude: "^project/"

  # https://github.com/igorshubovych/markdownlint-cli/tags
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.37.0"
    hooks:
      - id: markdownlint-fix
        name: markdownlint

  # https://github.com/adrienverge/yamllint/tags
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.32.0"
    hooks:
      - id: yamllint
        entry: yamllint --strict

  # https://github.com/pecigonzalo/pre-commit-shfmt/tags
  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: "v2.1.0"
    hooks:
      - id: shell-fmt-go

  # https://github.com/koalaman/shellcheck-precommit/tags
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: "v0.9.0"
    hooks:
      - id: shellcheck
        name: shellcheck

  # https://github.com/rhysd/actionlint/tags
  - repo: https://github.com/rhysd/actionlint
    rev: "v1.6.26"
    hooks:
      - id: actionlint-docker
        name: actionlint

  # https://github.com/bridgecrewio/checkov/tags
  - repo: https://github.com/bridgecrewio/checkov
    rev: "3.0.24"
    hooks:
      - id: checkov
        name: checkov
        args: [--config-file=.checkov.yml]

  # https://github.com/jorisroovers/gitlint/tags
  - repo: https://github.com/jorisroovers/gitlint
    rev: "v0.19.1"
    hooks:
      - id: gitlint

  # https://github.com/get-woke/woke/tags
  - repo: https://github.com/get-woke/woke
    rev: "v0.19.0"
    hooks:
      - id: woke-from-source
        args: [--config=.woke.yaml]

  - repo: local
    hooks:
      - id: lint
        name: Run Linters
        entry: make lint
        language: system
        always_run: true
        verbose: true
        pass_filenames: false
