---
name: go-optional

on:
  schedule:
    - cron: "30 0 * * 0"

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  go-modules:
    uses: remerge/workflows/.github/workflows/go-modules.yml@main
    secrets:
      ssh_key: ${{ secrets.DEPLOY_USER_SSH_KEY }}
